### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by wcxily** [kul-optec/alpaqa#9]
when i installed c++ version of alpaqa in windows and linux system, there were many bugs. i have tired many times, but i still can not install it. i think there are many aspect that can be improved.

**Comment by tttapa** [comment]
Hi,

Thanks for the feedback! Could you please post the specific errors you're seeing? If there are any errors during compilation, this is usually caused by using an older compiler. Building alpaqa on Linux requires GCC 11 or higher, and on Windows it requires Visual Studio 2022.

On newer systems (e.g. Ubuntu 22.04 or Debian Bookworm), the installation instructions should work without issues. (I noticed that the minimum requirement for Clang was outdated. This has now been updated in the documentation.)

If you intend to use alpaqa in your own C++ project, I would recommend installing it through a package manager such as Conan. You can find details in https://github.com/kul-optec/alpaqa/tree/develop/examples/CMake/Solver.

**Comment by wcxily** [comment]
> Hi,
> 
> Thanks for the feedback! Could you please post the specific errors you're seeing? If there are any errors during compilation, this is usually caused by using an older compiler. Building alpaqa on Linux requires GCC 11 or higher, and on Windows it requires Visual Studio 2022.
> 
> On newer systems (e.g. Ubuntu 22.04 or Debian Bookworm), the installation instructions should work without issues. (I noticed that the minimum requirement for Clang was outdated. This has now been updated in the documentation.)
> 
> If you intend to use alpaqa in your own C++ project, I would recommend installing it through a package manager such as Conan. You can find details in https://github.com/kul-optec/alpaqa/tree/develop/examples/CMake/Solver.

Hello, thank you very much for your reply. I have successfully installed C++ alpaqa in Ubuntu22.04.2 system.  When I test 
examples you provided，simple examples can be successfully compiled and run, but CasADi example can't be compiled successfully, terminal display “  error: ‘ROSENBROCK_FUNC_DLL’ was not declared in this scope”. Looking forward to your reply.
![2521b2bfa1a0de5218bc5d9fc3950f3](https://github.com/kul-optec/alpaqa/assets/162935345/51af2614-c595-4b7a-b114-790248ae3793)

**Comment by wcxily** [comment]
> Hi,
> 
> Thanks for the feedback! Could you please post the specific errors you're seeing? If there are any errors during compilation, this is usually caused by using an older compiler. Building alpaqa on Linux requires GCC 11 or higher, and on Windows it requires Visual Studio 2022.
> 
> On newer systems (e.g. Ubuntu 22.04 or Debian Bookworm), the installation instructions should work without issues. (I noticed that the minimum requirement for Clang was outdated. This has now been updated in the documentation.)
> 
> If you intend to use alpaqa in your own C++ project, I would recommend installing it through a package manager such as Conan. You can find details in https://github.com/kul-optec/alpaqa/tree/develop/examples/CMake/Solver.

Thank you very much for your reply, I have solved this problem :)

**Comment by tttapa** [comment]
Glad to hear it works. Feel free to open a [discussion](https://github.com/kul-optec/alpaqa/discussions) if you have any further questions.
